version: "3.9"

services:
  ollama:
    image: docker.arvancloud.ir/ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped

    ports:
      - "11434:11434"

    environment:
      - OLLAMA_HOST=0.0.0.0:11434

    volumes:
      - ollama:/root/.ollama
    # docker exec -it ollama ollama pull qwen2.5:7b-instruct

volumes:
  ollama:
